Repository akiomik/mado, pull requests merged in 2025-01, with the labels that each got.

#9 Add code_blocks and tables to MD013
  README.md
  src/config/lint/md013.rs
  src/document.rs
  src/rule/md013.rs
  src/service/linter.rs
Labels: enhancement

#10 Fix config
  README.md
  src/config.rs
Labels: bug

#49 Improve regex patterns
  src/rule/md013.rs
  src/rule/md037.rs
Labels: enhancement

#65 Move release.yml to .github/
  .github/release.yml
Labels: misc

#66 Bump version to 0.1.4
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  action/entrypoint.sh
Labels: misc

#67 Update packages to v0.1.4
  flake.nix
  justfile
  pkg/homebrew/mado.rb
  pkg/scoop/mado.json
Labels: misc

#72 Update README.md
  README.md
Labels: documentation

#73 Fix use_self
  src/config/lint/md002.rs
  src/config/lint/md003.rs
  src/config/lint/md004.rs
  src/config/lint/md007.rs
  src/config/lint/md013.rs
  src/config/lint/md025.rs
  src/config/lint/md026.rs
  src/config/lint/md029.rs
  src/config/lint/md030.rs
  src/config/lint/md033.rs
  src/config/lint/md035.rs
  src/config/lint/md036.rs
  src/config/lint/md041.rs
  src/config/lint/md046.rs
Labels: misc

#74 Winget
  .github/workflows/ci-pkg.yml
  README.md
  pkg/winget/mado.yml
Labels: enhancement

#76 Add test for ParallelLintRunner#run
  src/service/runner.rs
Labels: misc

#78 feat: add --quiet flag
  src/command.rs
  src/command/check.rs
  src/config/lint.rs
  src/main.rs
Labels: enhancement

#79 ci: update .github/release.yml
  .github/release.yml
Labels: ci

#81 feat: add Serialize for Config
  src/config.rs
  src/config/lint.rs
  src/config/lint/md002.rs
  src/config/lint/md003.rs
  src/config/lint/md004.rs
  src/config/lint/md007.rs
  src/config/lint/md013.rs
  src/config/lint/md025.rs
  src/config/lint/md026.rs
  src/config/lint/md029.rs
  src/config/lint/md030.rs
  src/config/lint/md033.rs
  src/config/lint/md035.rs
  src/config/lint/md036.rs
  src/config/lint/md041.rs
  src/config/lint/md046.rs
  src/output.rs
  src/rule/md003.rs
  src/rule/md004.rs
  src/rule/md029.rs
  src/rule/md035.rs
  src/rule/md046.rs
Labels: enhancement

#80 fix: respect config with --quiet
  Cargo.lock
  Cargo.toml
  mado.toml
  src/command/check.rs
  tests/command_check.rs
Labels: bug, dependencies

#83 chore: remove unnecessary categories in .github/release.yml
  .github/release.yml
Labels: chore

#82 chore: bump version to 0.1.5
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  action/entrypoint.sh
Labels: chore

#84 chore: add update-winget to justfile
  justfile
Labels: chore

#87 chore: add breaking change to .github/release.yml
  .github/release.yml
Labels: chore

#89 feat: add stdin support to check
  justfile
  src/command/check.rs
  src/service/runner.rs
  tests/command_check.rs
Labels: enhancement

#90 Taplo ci
  .github/workflows/taplo.yml
  .taplo.toml
  Cargo.toml
  justfile
Labels: chore, style, ci

#86 fix!: rename config keys in [lint.md030]
  mado.toml
  src/config/lint/md030.rs
Labels: bug, breaking change

#88 feat: json schema support
  .taplo.toml
  README.md
  pkg/json-schema/mado.json
  scripts/benchmarks/mado.toml
Labels: documentation, enhancement, chore, ci

#91 feat!: change style format for [lint.md035]
  pkg/json-schema/mado.json
  src/config/lint/md035.rs
  src/rule/md035.rs
Labels: enhancement, breaking change

#96 fix: check command with empty stdin
  src/command/check.rs
  src/service/runner.rs
  tests/command_check.rs
Labels: bug

#97 chore: disable MD024 in mado.toml
  mado.toml
  src/command/check.rs
  src/config.rs
Labels: chore

#99 test: fix check_quiet_with_config
  tests/command_check.rs
Labels: test

#98 chore: bump version to v0.2.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  action/entrypoint.sh
Labels: chore
